import { useMemo, useState } from 'react';
import { isInAigram, openAigramProfile, telegramId } from '@shared/runtime';
import { t } from '../i18n';
import type { Broadcast, WallEntry } from '../types';
import FrequencyCard from './FrequencyCard';

function isSelf(e:WallEntry){return e.userId==='self'||String(telegramId||'')===e.userId}
function Author({entry}:{entry:WallEntry}){if(isSelf(entry))return <span className="hw-author hw-author--self">{t('you')}</span>;return <button className="hw-author" disabled={!isInAigram} onClick={ev=>{ev.stopPropagation();if(isInAigram)openAigramProfile(entry.userId)}}><span className="hw-author__avatar">{entry.userAvatarUrl?<img src={entry.userAvatarUrl} alt="" draggable={false}/>:<b>{(entry.userName||'?')[0].toUpperCase()}</b>}</span><span className="hw-author__name">{entry.userName||'Unknown signal'}</span></button>}

export default function Wall({community,mine,loaded,onBack,onDelete}:{community:WallEntry[];mine:Broadcast[];loaded:boolean;onBack:()=>void;onDelete:(id:string)=>void}){
  const [selected,setSelected]=useState<WallEntry|null>(null),[confirmDelete,setConfirmDelete]=useState(false);
  const entries=useMemo(()=>{const cloudIds=new Set(community.map(e=>e.broadcast.id));const local:WallEntry[]=mine.filter(x=>!cloudIds.has(x.id)).map(x=>({userId:'self',userName:t('you'),broadcast:x}));return[...local,...community].sort((a,b)=>b.broadcast.createdAt-a.broadcast.createdAt).slice(0,24)},[community,mine]);
  const closeDetail=()=>{setSelected(null);setConfirmDelete(false)};
  const removeSelected=()=>{if(!selected||!isSelf(selected))return;if(!confirmDelete){setConfirmDelete(true);return}onDelete(selected.broadcast.id);closeDetail()};
  return <section className="hw-wall"><header><button onPointerDown={onBack}>←</button><div><small>HEARTWAVE ARCHIVE</small><h1>{t('community')}</h1></div><span>{String(entries.length).padStart(2,'0')}</span></header><div className="hw-wall__scroll">{!loaded?<div className="hw-wall__empty">◌<p>{t('loading')}</p></div>:entries.length===0?<div className="hw-wall__empty">⌁<h2>{t('empty')}</h2><p>{t('emptySub')}</p></div>:entries.map(e=><article className="hw-wall__item" key={e.broadcast.id} role="button" tabIndex={0} onClick={()=>{setSelected(e);setConfirmDelete(false)}} onKeyDown={ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();setSelected(e);setConfirmDelete(false)}}}><FrequencyCard compact broadcast={e.broadcast}/><footer><Author entry={e}/><span className="hw-wall__open">{t('detail')} ↗</span><time>{new Date(e.broadcast.createdAt).toLocaleDateString()}</time></footer></article>)}</div>{selected&&<div className="hw-detail" role="dialog" aria-modal="true" aria-label={t('detail')} onClick={closeDetail}><div className="hw-detail__sheet" onClick={ev=>ev.stopPropagation()}><header><small>{t('detail')}</small><button onClick={closeDetail} aria-label={t('close')}>×</button></header><div className="hw-detail__scroll"><FrequencyCard broadcast={selected.broadcast}/>{selected.broadcast.transmission&&<blockquote><small>{t('transmission')}</small>“{selected.broadcast.transmission}”<b>{selected.broadcast.signature}</b></blockquote>}<div className="hw-detail__author"><Author entry={selected}/><time>{new Date(selected.broadcast.createdAt).toLocaleString()}</time></div></div>{isSelf(selected)&&<div className="hw-detail__delete-wrap"><button className={`hw-detail__delete ${confirmDelete?'is-confirming':''}`} onClick={removeSelected}>{confirmDelete?t('deleteConfirm'):t('deleteMine')}</button>{confirmDelete&&<small>{t('deleteHint')}</small>}</div>}<button className="hw-detail__close" onClick={closeDetail}>{t('close')}</button></div></div>}</section>;
}
