export type Locale = 'zh' | 'en';
export function detectLocale(): Locale {
  const override = localStorage.getItem('game_locale');
  if (override === 'zh' || override === 'en') return override;
  return navigator.language.toLowerCase().startsWith('zh') ? 'zh' : 'en';
}
const copy = {
  zh: { titleTop:'心动', titleBottom:'电台', live:'午夜直播 · 只对同频的人开放', start:'开始调频', startSub:'5 个选择，生成并播出今晚的频道', generated:'今晚的频率已播出', generatedSub:'打开频率墙查看你的作品', generationUsed:'今晚已经生成过了', generationUsedSub:'生成额度明晚恢复', wall:'听听大家', round:'信号', choose:'别想太久，第一反应最准', score:'能量', result:'你的今晚频道', published:'今晚已正式播出', publishing:'正在将今晚的频率送上电台…', deletedToday:'今晚作品已删除 · 生成额度已使用', dailyRitual:'每晚只生成一次；作品完成后自动播出。', viewWall:'打开频率墙', tomorrow:'明晚再调频', home:'返回首页', best:'历史最高', you:'你', empty:'今晚还没人开台', emptySub:'成为第一个留下频率的人', back:'返回', community:'社区频率', loading:'正在搜寻附近信号…', lost:'信号丢失', streak:'连续同频', close:'关闭广播', detail:'完整广播', transmission:'午夜播报', deleteMine:'删除我的广播', deleteConfirm:'再次点击，确认删除', deleteHint:'删除后无法恢复，且不会返还今日生成额度。' },
  en: { titleTop:'HEART', titleBottom:'WAVE', live:'MIDNIGHT LIVE · FOR KINDRED SIGNALS', start:'TUNE IN', startSub:'5 choices to generate and air tonight’s channel', generated:'TONIGHT’S SIGNAL IS LIVE', generatedSub:'Open the wall to view your broadcast', generationUsed:'TONIGHT’S GENERATION IS USED', generationUsedSub:'Your generation returns tomorrow', wall:'LISTEN IN', round:'SIGNAL', choose:'Don’t overthink it. First instinct wins.', score:'ENERGY', result:'YOUR NIGHT CHANNEL', published:'TONIGHT’S SIGNAL IS LIVE', publishing:'SENDING TONIGHT’S SIGNAL TO THE AIR…', deletedToday:'TONIGHT’S WORK WAS DELETED · GENERATION USED', dailyRitual:'One generation each night. Every finished work airs automatically.', viewWall:'OPEN FREQUENCY WALL', tomorrow:'TUNE AGAIN TOMORROW', home:'BACK HOME', best:'PERSONAL BEST', you:'YOU', empty:'NO ONE IS LIVE YET', emptySub:'Be the first signal in the night', back:'BACK', community:'COMMUNITY FREQUENCIES', loading:'SCANNING NEARBY SIGNALS…', lost:'SIGNAL LOST', streak:'SAME WAVE', close:'CLOSE BROADCAST', detail:'FULL BROADCAST', transmission:'MIDNIGHT TRANSMISSION', deleteMine:'DELETE MY BROADCAST', deleteConfirm:'TAP AGAIN TO DELETE', deleteHint:'This cannot be undone and will not restore today’s generation.' },
};
export function t(key: keyof typeof copy.zh) { return copy[detectLocale()][key]; }
